export const ERROR_CODES = {
  VALIDATION_ERROR: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  INVALID_TRANSITION: 409,
  CONFLICT: 409,
  PAYLOAD_TOO_LARGE: 413,
  UNSUPPORTED_MEDIA_TYPE: 415,
  INTERNAL_ERROR: 500
};

export const DEPARTMENTS = ["FACILITIES", "IT", "SECURITY", "HR"];
export const PRIORITIES = ["LOW", "MEDIUM", "HIGH"];
export const STATUSES = ["NEW", "IN_PROGRESS", "BLOCKED", "DONE"];

export const STATUS_TRANSITIONS = {
  NEW: ["IN_PROGRESS"],
  IN_PROGRESS: ["BLOCKED", "DONE"],
  BLOCKED: ["IN_PROGRESS"],
  DONE: []
};
